apiVersion: apps/v1
kind: Deployment
metadata:
  name: fronted
  labels:
    app: frontend
spec:
  replica: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: lisandrodv27/frontend-build:latest
        ports: 
        - containerPort: 80
