- hosts: all
  become: true
  roles:
    - nginx
    - role: docker
      vars:
        DCKR_PACKAGES:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - role: jenkins
  # - pytest
