- hosts: all
  become: true
  roles:
    - jenkins
    - role: docker
      vars:
        DCKR_PACKAGES:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - role: nginx
      vars: 
        install_directory: /opt/static-website-example
  # - pytest
