- hosts: all
  become: true
  roles:
    - jenkins
    - role: docker
      vars:
        DCKR_PACKAGES:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-pip
        - mysql-client
        - jq
    - role: k8s
      vars:
        packages:
          - kubelet 
          - kubeadm 
          - kubectl
    - role: awscli
